server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/shinemo?useSSL=true&enabledTLSProtocols=TLSv1.2
  redis:
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
baas:
  role: 1,2,3,4